# Github workflow to run pytest on new prs and pushes to main
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: pytest
on:
    pull_request:
    push:
        branches: [main]
jobs:
    # Only supporting python 3.10+ for now
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10", "3.11"]
        # proactively cancel the same job running on the same branch when a newer
        # one comes in
        concurrency:
            group: ${{ github.ref }}-${{ matrix.python-version }}
            cancel-in-progress: true
        steps:
            - uses: actions/checkout@v2

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install poetry
              uses: abatilo/actions-poetry@v2

            - uses: actions/cache@v3
              name: Define a cache for the virtual environment based on the dependencies lock file
              with:
                  path: ./.venv
                  key: venv-${{ hashFiles('poetry.lock') }}-${{ matrix.python-version }}

            - name: Install the project dependencies
              run: poetry install

            - name: Run the tests
              run: poetry run pytest -v

            - name: Run pylint
              run: poetry run pylint --errors-only im_openai
