# Github workflow to run pytest on new prs and pushes to main
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: pytest
on:
    pull_request:
    push:
        branches: [main]
jobs:
    # Only supporting python 3.10+ for now
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10", "3.11"]
        # proactively cancel the same job running on the same branch when a newer
        # one comes in
        concurrency:
            group: ${{ github.ref }}-${{ matrix.python-version }}
            cancel-in-progress: true
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  # hack: install langchain here for tests
                  python -m pip install langchain
            - name: Run tests
              run: |
                  pytest
